version: "3.8"

volumes:
  databases:
  gems:

services:
  pg:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - databases:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "bundle && rails db:create db:migrate && rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    ports:
      - 3000:3000
    volumes:
      - ./:/src
      - gems:/usr/local/bundle
    environment:
      POSTGRES_HOST: pg
      POSTGRES_USER: postgres
    depends_on:
      - pg
