name: CI Pipeline
on:
  push:
    branches: [master,main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push image to Amazon ECR
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          registry: ${{ steps.login-ecr.outputs.registry }}
          repo: docker-images
          image_tag: ${{ github.sha }}
        with:
          push: true
          tags: ${{ env.registry }}/${{ env.repo }}:${{ env.image_tag }}


